before_script:
  - make init

# EzMake defaults to building and running all tests
test_all:
  script:
    - make build MODE=dynamic
    - make test
    - make clean
    - make build MODE=dynamic
    - make test
