language: c
install:
script:
- make init
- make build MODE=static
- echo "EzMake developers" >> test
- echo "/q" >> test
- echo "" >> test
- make run IN=test
- make clean
- make build MODE=dynamic
- make run IN=test

